/**
 * Topic Researcher - Generates well-researched template topics
 * Focused on Software Management, Operations, and Lifecycle
 */

export interface TemplateTopic {
  name: string;
  description: string;
  category: string;
  icon: string;
  blocks: TopicBlock[];
}

export interface TopicBlock {
  type: string;
  text?: string;
  content?: string;
  [key: string]: any;
}

/**
 * Curated list of well-researched template topics for Software Management
 */
const TEMPLATE_TOPICS: TemplateTopic[] = [
  // Software Project Management
  {
    name: "Software Project Management Dashboard",
    description: "Comprehensive dashboard for managing software projects, timelines, and resources",
    category: "Software Management",
    icon: "📊",
    blocks: [
      { type: "heading_1", text: "📊 Software Project Management Dashboard" },
      { type: "heading_2", text: "Project Overview" },
      { type: "paragraph", text: "Project Name: " },
      { type: "paragraph", text: "Status: Planning / In Progress / On Hold / Completed" },
      { type: "paragraph", text: "Start Date: " },
      { type: "paragraph", text: "Target Release: " },
      { type: "heading_2", text: "Team & Resources" },
      { type: "bulleted_list_item", text: "Project Manager: " },
      { type: "bulleted_list_item", text: "Tech Lead: " },
      { type: "bulleted_list_item", text: "Developers: " },
      { type: "bulleted_list_item", text: "QA Engineers: " },
      { type: "bulleted_list_item", text: "Designers: " },
      { type: "heading_2", text: "Key Metrics" },
      { type: "paragraph", text: "Budget: $" },
      { type: "paragraph", text: "Budget Used: $" },
      { type: "paragraph", text: "Timeline Progress: " },
      { type: "paragraph", text: "Tasks Completed: " },
      { type: "paragraph", text: "Tasks Remaining: " },
      { type: "heading_2", text: "Milestones" },
      { type: "to_do", text: "Milestone 1: Description - Due Date", checked: false },
      { type: "to_do", text: "Milestone 2: Description - Due Date", checked: false },
      { type: "to_do", text: "Milestone 3: Description - Due Date", checked: false },
      { type: "heading_2", text: "Risks & Issues" },
      { type: "bulleted_list_item", text: "Risk 1: Description - Mitigation" },
      { type: "bulleted_list_item", text: "Issue 1: Description - Status" },
      { type: "heading_2", text: "Stakeholders" },
      { type: "bulleted_list_item", text: "Stakeholder 1: Role - Contact" },
      { type: "bulleted_list_item", text: "Stakeholder 2: Role - Contact" },
      { type: "heading_2", text: "Next Actions" },
      { type: "to_do", text: "Action 1", checked: false },
      { type: "to_do", text: "Action 2", checked: false },
    ],
  },
  {
    name: "Software Release Management Plan",
    description: "Plan and coordinate software releases across environments",
    category: "Software Management",
    icon: "🚀",
    blocks: [
      { type: "heading_1", text: "🚀 Software Release Management Plan" },
      { type: "heading_2", text: "Release Information" },
      { type: "paragraph", text: "Release Version: " },
      { type: "paragraph", text: "Release Type: Major / Minor / Patch / Hotfix" },
      { type: "paragraph", text: "Target Release Date: " },
      { type: "paragraph", text: "Release Manager: " },
      { type: "heading_2", text: "Release Scope" },
      { type: "bulleted_list_item", text: "Feature 1: Description" },
      { type: "bulleted_list_item", text: "Feature 2: Description" },
      { type: "bulleted_list_item", text: "Bug Fix 1: Description" },
      { type: "heading_2", text: "Environments" },
      { type: "heading_3", text: "Development" },
      { type: "to_do", text: "Deploy to Dev", checked: false },
      { type: "to_do", text: "Smoke tests passed", checked: false },
      { type: "heading_3", text: "Staging" },
      { type: "to_do", text: "Deploy to Staging", checked: false },
      { type: "to_do", text: "QA testing completed", checked: false },
      { type: "to_do", text: "UAT sign-off", checked: false },
      { type: "heading_3", text: "Production" },
      { type: "to_do", text: "Pre-deployment checklist completed", checked: false },
      { type: "to_do", text: "Deploy to Production", checked: false },
      { type: "to_do", text: "Post-deployment verification", checked: false },
      { type: "heading_2", text: "Rollback Plan" },
      { type: "paragraph", text: "Rollback procedure: " },
      { type: "paragraph", text: "Rollback trigger conditions: " },
      { type: "heading_2", text: "Communication Plan" },
      { type: "to_do", text: "Release notes prepared", checked: false },
      { type: "to_do", text: "Stakeholders notified", checked: false },
      { type: "to_do", text: "Support team briefed", checked: false },
      { type: "heading_2", text: "Post-Release" },
      { type: "paragraph", text: "Monitoring period: " },
      { type: "to_do", text: "Monitor error rates", checked: false },
      { type: "to_do", text: "Monitor performance metrics", checked: false },
      { type: "to_do", text: "Collect user feedback", checked: false },
    ],
  },
  {
    name: "Software Quality Management Dashboard",
    description: "Track software quality metrics, test coverage, and quality gates",
    category: "Software Management",
    icon: "✅",
    blocks: [
      { type: "heading_1", text: "✅ Software Quality Management Dashboard" },
      { type: "heading_2", text: "Quality Metrics" },
      { type: "paragraph", text: "Code Coverage: " },
      { type: "paragraph", text: "Test Pass Rate: " },
      { type: "paragraph", text: "Bug Density: " },
      { type: "paragraph", text: "Technical Debt Score: " },
      { type: "heading_2", text: "Test Results" },
      { type: "heading_3", text: "Unit Tests" },
      { type: "paragraph", text: "Total: " },
      { type: "paragraph", text: "Passed: " },
      { type: "paragraph", text: "Failed: " },
      { type: "heading_3", text: "Integration Tests" },
      { type: "paragraph", text: "Total: " },
      { type: "paragraph", text: "Passed: " },
      { type: "paragraph", text: "Failed: " },
      { type: "heading_3", text: "E2E Tests" },
      { type: "paragraph", text: "Total: " },
      { type: "paragraph", text: "Passed: " },
      { type: "paragraph", text: "Failed: " },
      { type: "heading_2", text: "Code Quality" },
      { type: "paragraph", text: "Code Review Coverage: " },
      { type: "paragraph", text: "Code Smells: " },
      { type: "paragraph", text: "Security Vulnerabilities: " },
      { type: "heading_2", text: "Quality Gates" },
      { type: "to_do", text: "Code coverage > 80%", checked: false },
      { type: "to_do", text: "All tests passing", checked: false },
      { type: "to_do", text: "No critical bugs", checked: false },
      { type: "to_do", text: "Security scan passed", checked: false },
      { type: "to_do", text: "Performance benchmarks met", checked: false },
      { type: "heading_2", text: "Quality Issues" },
      { type: "bulleted_list_item", text: "Issue 1: Description - Priority" },
      { type: "bulleted_list_item", text: "Issue 2: Description - Priority" },
      { type: "heading_2", text: "Action Items" },
      { type: "to_do", text: "Action 1", checked: false },
      { type: "to_do", text: "Action 2", checked: false },
    ],
  },
  {
    name: "Software Maintenance Schedule",
    description: "Plan and track software maintenance activities, updates, and patches",
    category: "Software Management",
    icon: "🔧",
    blocks: [
      { type: "heading_1", text: "🔧 Software Maintenance Schedule" },
      { type: "heading_2", text: "Maintenance Overview" },
      { type: "paragraph", text: "Software Name: " },
      { type: "paragraph", text: "Current Version: " },
      { type: "paragraph", text: "Maintenance Window: " },
      { type: "heading_2", text: "Scheduled Maintenance" },
      { type: "heading_3", text: "Upcoming Maintenance" },
      { type: "to_do", text: "Maintenance 1: Date - Description", checked: false },
      { type: "to_do", text: "Maintenance 2: Date - Description", checked: false },
      { type: "heading_2", text: "Maintenance Types" },
      { type: "heading_3", text: "Preventive Maintenance" },
      { type: "bulleted_list_item", text: "Database optimization" },
      { type: "bulleted_list_item", text: "Security updates" },
      { type: "bulleted_list_item", text: "Performance tuning" },
      { type: "heading_3", text: "Corrective Maintenance" },
      { type: "bulleted_list_item", text: "Bug fixes" },
      { type: "bulleted_list_item", text: "Error corrections" },
      { type: "heading_3", text: "Adaptive Maintenance" },
      { type: "bulleted_list_item", text: "OS updates" },
      { type: "bulleted_list_item", text: "Dependency updates" },
      { type: "heading_2", text: "Dependency Management" },
      { type: "paragraph", text: "Outdated dependencies: " },
      { type: "paragraph", text: "Security vulnerabilities: " },
      { type: "to_do", text: "Update dependency 1", checked: false },
      { type: "to_do", text: "Update dependency 2", checked: false },
      { type: "heading_2", text: "Maintenance Log" },
      { type: "bulleted_list_item", text: "Date: Activity - Result" },
      { type: "bulleted_list_item", text: "Date: Activity - Result" },
      { type: "heading_2", text: "Next Maintenance Tasks" },
      { type: "to_do", text: "Task 1", checked: false },
      { type: "to_do", text: "Task 2", checked: false },
    ],
  },
  {
    name: "Software Operations Runbook",
    description: "Standard operating procedures for software operations and incident response",
    category: "Software Management",
    icon: "📖",
    blocks: [
      { type: "heading_1", text: "📖 Software Operations Runbook" },
      { type: "heading_2", text: "System Overview" },
      { type: "paragraph", text: "System Name: " },
      { type: "paragraph", text: "Environment: Production / Staging / Development" },
      { type: "paragraph", text: "Infrastructure: " },
      { type: "heading_2", text: "Common Operations" },
      { type: "heading_3", text: "Deployment" },
      { type: "numbered_list_item", text: "Step 1: Pre-deployment checks" },
      { type: "numbered_list_item", text: "Step 2: Backup current version" },
      { type: "numbered_list_item", text: "Step 3: Deploy new version" },
      { type: "numbered_list_item", text: "Step 4: Verify deployment" },
      { type: "heading_3", text: "Rollback" },
      { type: "numbered_list_item", text: "Step 1: Identify issue" },
      { type: "numbered_list_item", text: "Step 2: Stop deployment" },
      { type: "numbered_list_item", text: "Step 3: Restore previous version" },
      { type: "heading_2", text: "Monitoring & Alerts" },
      { type: "bulleted_list_item", text: "Key Metrics: CPU, Memory, Disk, Network" },
      { type: "bulleted_list_item", text: "Application Metrics: Response time, Error rate" },
      { type: "bulleted_list_item", text: "Alert Thresholds: " },
      { type: "heading_2", text: "Incident Response" },
      { type: "heading_3", text: "Severity Levels" },
      { type: "bulleted_list_item", text: "P1 - Critical: System down" },
      { type: "bulleted_list_item", text: "P2 - High: Major feature broken" },
      { type: "bulleted_list_item", text: "P3 - Medium: Minor issue" },
      { type: "heading_3", text: "Response Procedures" },
      { type: "numbered_list_item", text: "Acknowledge incident" },
      { type: "numbered_list_item", text: "Assess impact" },
      { type: "numbered_list_item", text: "Contain issue" },
      { type: "numbered_list_item", text: "Resolve issue" },
      { type: "numbered_list_item", text: "Post-mortem" },
      { type: "heading_2", text: "Contacts" },
      { type: "bulleted_list_item", text: "On-Call Engineer: " },
      { type: "bulleted_list_item", text: "Team Lead: " },
      { type: "bulleted_list_item", text: "Escalation Contact: " },
    ],
  },
  {
    name: "Software Architecture Management",
    description: "Document and manage software architecture decisions and evolution",
    category: "Software Management",
    icon: "🏗️",
    blocks: [
      { type: "heading_1", text: "🏗️ Software Architecture Management" },
      { type: "heading_2", text: "Architecture Overview" },
      { type: "paragraph", text: "System Name: " },
      { type: "paragraph", text: "Architecture Pattern: Monolith / Microservices / Serverless / etc." },
      { type: "paragraph", text: "Last Updated: " },
      { type: "heading_2", text: "System Components" },
      { type: "heading_3", text: "Component 1" },
      { type: "paragraph", text: "Purpose: " },
      { type: "paragraph", text: "Technology: " },
      { type: "paragraph", text: "Dependencies: " },
      { type: "heading_3", text: "Component 2" },
      { type: "paragraph", text: "Purpose: " },
      { type: "paragraph", text: "Technology: " },
      { type: "paragraph", text: "Dependencies: " },
      { type: "heading_2", text: "Architecture Decisions" },
      { type: "heading_3", text: "Decision 1" },
      { type: "paragraph", text: "Context: " },
      { type: "paragraph", text: "Decision: " },
      { type: "paragraph", text: "Rationale: " },
      { type: "paragraph", text: "Consequences: " },
      { type: "heading_2", text: "Data Flow" },
      { type: "paragraph", text: "How data flows through the system: " },
      { type: "heading_2", text: "Technology Stack" },
      { type: "bulleted_list_item", text: "Frontend: " },
      { type: "bulleted_list_item", text: "Backend: " },
      { type: "bulleted_list_item", text: "Database: " },
      { type: "bulleted_list_item", text: "Infrastructure: " },
      { type: "heading_2", text: "Scalability Considerations" },
      { type: "bulleted_list_item", text: "Horizontal scaling: " },
      { type: "bulleted_list_item", text: "Vertical scaling: " },
      { type: "bulleted_list_item", text: "Load balancing: " },
      { type: "heading_2", text: "Security Architecture" },
      { type: "bulleted_list_item", text: "Authentication: " },
      { type: "bulleted_list_item", text: "Authorization: " },
      { type: "bulleted_list_item", text: "Data encryption: " },
      { type: "heading_2", text: "Evolution Plan" },
      { type: "bulleted_list_item", text: "Planned changes: " },
      { type: "bulleted_list_item", text: "Migration strategy: " },
    ],
  },
  {
    name: "Software Team Management",
    description: "Manage software team structure, responsibilities, and performance",
    category: "Software Management",
    icon: "👥",
    blocks: [
      { type: "heading_1", text: "👥 Software Team Management" },
      { type: "heading_2", text: "Team Overview" },
      { type: "paragraph", text: "Team Name: " },
      { type: "paragraph", text: "Team Lead: " },
      { type: "paragraph", text: "Team Size: " },
      { type: "heading_2", text: "Team Members" },
      { type: "heading_3", text: "Member 1" },
      { type: "paragraph", text: "Role: " },
      { type: "paragraph", text: "Responsibilities: " },
      { type: "paragraph", text: "Skills: " },
      { type: "heading_3", text: "Member 2" },
      { type: "paragraph", text: "Role: " },
      { type: "paragraph", text: "Responsibilities: " },
      { type: "paragraph", text: "Skills: " },
      { type: "heading_2", text: "Team Structure" },
      { type: "bulleted_list_item", text: "Backend Developers: " },
      { type: "bulleted_list_item", text: "Frontend Developers: " },
      { type: "bulleted_list_item", text: "QA Engineers: " },
      { type: "bulleted_list_item", text: "DevOps Engineers: " },
      { type: "bulleted_list_item", text: "Product Managers: " },
      { type: "heading_2", text: "Responsibilities Matrix" },
      { type: "paragraph", text: "Who is responsible for what: " },
      { type: "heading_2", text: "Team Goals" },
      { type: "to_do", text: "Goal 1: Description - Deadline", checked: false },
      { type: "to_do", text: "Goal 2: Description - Deadline", checked: false },
      { type: "heading_2", text: "Performance Metrics" },
      { type: "paragraph", text: "Velocity: " },
      { type: "paragraph", text: "Code Quality: " },
      { type: "paragraph", text: "Delivery Rate: " },
      { type: "heading_2", text: "Team Development" },
      { type: "bulleted_list_item", text: "Training needs: " },
      { type: "bulleted_list_item", text: "Skill gaps: " },
      { type: "bulleted_list_item", text: "Career development: " },
    ],
  },
  {
    name: "Software Documentation Management",
    description: "Manage software documentation, API docs, and knowledge base",
    category: "Software Management",
    icon: "📚",
    blocks: [
      { type: "heading_1", text: "📚 Software Documentation Management" },
      { type: "heading_2", text: "Documentation Overview" },
      { type: "paragraph", text: "Software Name: " },
      { type: "paragraph", text: "Documentation Version: " },
      { type: "paragraph", text: "Last Updated: " },
      { type: "heading_2", text: "Documentation Types" },
      { type: "heading_3", text: "User Documentation" },
      { type: "to_do", text: "User Guide", checked: false },
      { type: "to_do", text: "Getting Started Guide", checked: false },
      { type: "to_do", text: "FAQ", checked: false },
      { type: "heading_3", text: "Technical Documentation" },
      { type: "to_do", text: "API Documentation", checked: false },
      { type: "to_do", text: "Architecture Documentation", checked: false },
      { type: "to_do", text: "Deployment Guide", checked: false },
      { type: "to_do", text: "Configuration Guide", checked: false },
      { type: "heading_3", text: "Developer Documentation" },
      { type: "to_do", text: "Setup Guide", checked: false },
      { type: "to_do", text: "Contributing Guide", checked: false },
      { type: "to_do", text: "Code Style Guide", checked: false },
      { type: "heading_2", text: "Documentation Status" },
      { type: "bulleted_list_item", text: "Up to date: " },
      { type: "bulleted_list_item", text: "Needs update: " },
      { type: "bulleted_list_item", text: "Missing: " },
      { type: "heading_2", text: "Documentation Review" },
      { type: "paragraph", text: "Last review date: " },
      { type: "paragraph", text: "Next review date: " },
      { type: "to_do", text: "Review user docs", checked: false },
      { type: "to_do", text: "Review API docs", checked: false },
      { type: "to_do", text: "Review technical docs", checked: false },
      { type: "heading_2", text: "Documentation Tools" },
      { type: "bulleted_list_item", text: "Documentation platform: " },
      { type: "bulleted_list_item", text: "API documentation tool: " },
      { type: "bulleted_list_item", text: "Diagramming tool: " },
      { type: "heading_2", text: "Action Items" },
      { type: "to_do", text: "Update outdated docs", checked: false },
      { type: "to_do", text: "Create missing docs", checked: false },
    ],
  },
  {
    name: "Software Security Management",
    description: "Manage software security policies, vulnerabilities, and compliance",
    category: "Software Management",
    icon: "🔒",
    blocks: [
      { type: "heading_1", text: "🔒 Software Security Management" },
      { type: "heading_2", text: "Security Overview" },
      { type: "paragraph", text: "Software Name: " },
      { type: "paragraph", text: "Security Status: " },
      { type: "paragraph", text: "Last Security Audit: " },
      { type: "heading_2", text: "Security Policies" },
      { type: "bulleted_list_item", text: "Authentication policy: " },
      { type: "bulleted_list_item", text: "Authorization policy: " },
      { type: "bulleted_list_item", text: "Data encryption policy: " },
      { type: "bulleted_list_item", text: "Access control policy: " },
      { type: "heading_2", text: "Vulnerability Management" },
      { type: "heading_3", text: "Critical Vulnerabilities" },
      { type: "bulleted_list_item", text: "Vulnerability 1: Description - Status" },
      { type: "bulleted_list_item", text: "Vulnerability 2: Description - Status" },
      { type: "heading_3", text: "High Vulnerabilities" },
      { type: "bulleted_list_item", text: "Vulnerability 1: Description - Status" },
      { type: "heading_2", text: "Security Scanning" },
      { type: "to_do", text: "Dependency scan", checked: false },
      { type: "to_do", text: "Code security scan", checked: false },
      { type: "to_do", text: "Infrastructure scan", checked: false },
      { type: "to_do", text: "Penetration testing", checked: false },
      { type: "heading_2", text: "Compliance" },
      { type: "bulleted_list_item", text: "GDPR compliance: " },
      { type: "bulleted_list_item", text: "SOC 2 compliance: " },
      { type: "bulleted_list_item", text: "ISO 27001 compliance: " },
      { type: "heading_2", text: "Incident Response" },
      { type: "paragraph", text: "Security incident procedure: " },
      { type: "paragraph", text: "Contact: " },
      { type: "heading_2", text: "Security Training" },
      { type: "to_do", text: "Team security training scheduled", checked: false },
      { type: "to_do", text: "Security awareness program", checked: false },
      { type: "heading_2", text: "Action Items" },
      { type: "to_do", text: "Fix critical vulnerability", checked: false },
      { type: "to_do", text: "Update security policies", checked: false },
    ],
  },
  {
    name: "Software Performance Management",
    description: "Monitor and optimize software performance metrics",
    category: "Software Management",
    icon: "⚡",
    blocks: [
      { type: "heading_1", text: "⚡ Software Performance Management" },
      { type: "heading_2", text: "Performance Overview" },
      { type: "paragraph", text: "Software Name: " },
      { type: "paragraph", text: "Performance Status: Good / Degraded / Critical" },
      { type: "paragraph", text: "Last Assessment: " },
      { type: "heading_2", text: "Key Performance Indicators" },
      { type: "heading_3", text: "Response Time" },
      { type: "paragraph", text: "Average: " },
      { type: "paragraph", text: "P95: " },
      { type: "paragraph", text: "P99: " },
      { type: "heading_3", text: "Throughput" },
      { type: "paragraph", text: "Requests per second: " },
      { type: "paragraph", text: "Transactions per second: " },
      { type: "heading_3", text: "Resource Usage" },
      { type: "paragraph", text: "CPU Usage: " },
      { type: "paragraph", text: "Memory Usage: " },
      { type: "paragraph", text: "Disk I/O: " },
      { type: "paragraph", text: "Network I/O: " },
      { type: "heading_2", text: "Performance Targets" },
      { type: "bulleted_list_item", text: "Response time < 200ms (P95)" },
      { type: "bulleted_list_item", text: "Uptime > 99.9%" },
      { type: "bulleted_list_item", text: "Error rate < 0.1%" },
      { type: "heading_2", text: "Bottlenecks" },
      { type: "bulleted_list_item", text: "Bottleneck 1: Description - Impact" },
      { type: "bulleted_list_item", text: "Bottleneck 2: Description - Impact" },
      { type: "heading_2", text: "Optimization Actions" },
      { type: "to_do", text: "Optimize database queries", checked: false },
      { type: "to_do", text: "Implement caching", checked: false },
      { type: "to_do", text: "Optimize API endpoints", checked: false },
      { type: "heading_2", text: "Performance Testing" },
      { type: "paragraph", text: "Last load test: " },
      { type: "paragraph", text: "Results: " },
      { type: "heading_2", text: "Monitoring & Alerts" },
      { type: "bulleted_list_item", text: "Monitoring tools: " },
      { type: "bulleted_list_item", text: "Alert thresholds: " },
    ],
  },
  {
    name: "Software Change Management",
    description: "Manage software changes, updates, and version control",
    category: "Software Management",
    icon: "🔄",
    blocks: [
      { type: "heading_1", text: "🔄 Software Change Management" },
      { type: "heading_2", text: "Change Request" },
      { type: "paragraph", text: "Change ID: " },
      { type: "paragraph", text: "Requested by: " },
      { type: "paragraph", text: "Date: " },
      { type: "paragraph", text: "Priority: Low / Medium / High / Critical" },
      { type: "heading_2", text: "Change Description" },
      { type: "paragraph", text: "What needs to change: " },
      { type: "paragraph", text: "Why is this change needed: " },
      { type: "heading_2", text: "Impact Analysis" },
      { type: "bulleted_list_item", text: "Affected systems: " },
      { type: "bulleted_list_item", text: "Affected users: " },
      { type: "bulleted_list_item", text: "Risk level: " },
      { type: "bulleted_list_item", text: "Downtime required: " },
      { type: "heading_2", text: "Change Plan" },
      { type: "numbered_list_item", text: "Step 1: Preparation" },
      { type: "numbered_list_item", text: "Step 2: Implementation" },
      { type: "numbered_list_item", text: "Step 3: Testing" },
      { type: "numbered_list_item", text: "Step 4: Deployment" },
      { type: "heading_2", text: "Rollback Plan" },
      { type: "paragraph", text: "How to rollback if needed: " },
      { type: "heading_2", text: "Approval" },
      { type: "to_do", text: "Technical review", checked: false },
      { type: "to_do", text: "Security review", checked: false },
      { type: "to_do", text: "Change approval board", checked: false },
      { type: "heading_2", text: "Implementation" },
      { type: "paragraph", text: "Scheduled date: " },
      { type: "paragraph", text: "Implemented by: " },
      { type: "paragraph", text: "Status: " },
      { type: "heading_2", text: "Post-Implementation" },
      { type: "to_do", text: "Verify change", checked: false },
      { type: "to_do", text: "Monitor impact", checked: false },
      { type: "to_do", text: "Document change", checked: false },
    ],
  },
  {
    name: "Software License Management",
    description: "Track and manage software licenses, subscriptions, and compliance",
    category: "Software Management",
    icon: "📄",
    blocks: [
      { type: "heading_1", text: "📄 Software License Management" },
      { type: "heading_2", text: "License Overview" },
      { type: "paragraph", text: "Software Name: " },
      { type: "paragraph", text: "License Type: Commercial / Open Source / Free" },
      { type: "paragraph", text: "Total Licenses: " },
      { type: "paragraph", text: "Licenses Used: " },
      { type: "heading_2", text: "License Details" },
      { type: "heading_3", text: "License 1" },
      { type: "paragraph", text: "Provider: " },
      { type: "paragraph", text: "License Key: " },
      { type: "paragraph", text: "Purchase Date: " },
      { type: "paragraph", text: "Expiration Date: " },
      { type: "paragraph", text: "Renewal Date: " },
      { type: "paragraph", text: "Cost: $" },
      { type: "heading_2", text: "License Compliance" },
      { type: "to_do", text: "Audit licenses", checked: false },
      { type: "to_do", text: "Verify usage", checked: false },
      { type: "to_do", text: "Check expiration dates", checked: false },
      { type: "heading_2", text: "Upcoming Renewals" },
      { type: "bulleted_list_item", text: "License 1: Expires on [date]" },
      { type: "bulleted_list_item", text: "License 2: Expires on [date]" },
      { type: "heading_2", text: "Open Source Licenses" },
      { type: "bulleted_list_item", text: "Dependency 1: License type" },
      { type: "bulleted_list_item", text: "Dependency 2: License type" },
      { type: "heading_2", text: "License Costs" },
      { type: "paragraph", text: "Monthly cost: $" },
      { type: "paragraph", text: "Annual cost: $" },
      { type: "heading_2", text: "Action Items" },
      { type: "to_do", text: "Renew expiring license", checked: false },
      { type: "to_do", text: "Review license usage", checked: false },
    ],
  },
  {
    name: "Software Monitoring Dashboard",
    description: "Centralized dashboard for monitoring software health and metrics",
    category: "Software Management",
    icon: "📊",
    blocks: [
      { type: "heading_1", text: "📊 Software Monitoring Dashboard" },
      { type: "heading_2", text: "System Health" },
      { type: "paragraph", text: "Overall Status: Healthy / Warning / Critical" },
      { type: "paragraph", text: "Uptime: " },
      { type: "paragraph", text: "Last Updated: " },
      { type: "heading_2", text: "Application Metrics" },
      { type: "heading_3", text: "Performance" },
      { type: "paragraph", text: "Response Time (avg): " },
      { type: "paragraph", text: "Response Time (P95): " },
      { type: "paragraph", text: "Throughput: " },
      { type: "heading_3", text: "Errors" },
      { type: "paragraph", text: "Error Rate: " },
      { type: "paragraph", text: "Critical Errors: " },
      { type: "paragraph", text: "Warnings: " },
      { type: "heading_2", text: "Infrastructure Metrics" },
      { type: "heading_3", text: "CPU" },
      { type: "paragraph", text: "Usage: " },
      { type: "paragraph", text: "Status: " },
      { type: "heading_3", text: "Memory" },
      { type: "paragraph", text: "Usage: " },
      { type: "paragraph", text: "Status: " },
      { type: "heading_3", text: "Disk" },
      { type: "paragraph", text: "Usage: " },
      { type: "paragraph", text: "Status: " },
      { type: "heading_3", text: "Network" },
      { type: "paragraph", text: "Bandwidth: " },
      { type: "paragraph", text: "Status: " },
      { type: "heading_2", text: "Database Metrics" },
      { type: "paragraph", text: "Connection Pool: " },
      { type: "paragraph", text: "Query Performance: " },
      { type: "paragraph", text: "Replication Lag: " },
      { type: "heading_2", text: "Active Alerts" },
      { type: "bulleted_list_item", text: "Alert 1: Description - Severity" },
      { type: "bulleted_list_item", text: "Alert 2: Description - Severity" },
      { type: "heading_2", text: "Recent Incidents" },
      { type: "bulleted_list_item", text: "Incident 1: Date - Status" },
      { type: "bulleted_list_item", text: "Incident 2: Date - Status" },
      { type: "heading_2", text: "Trends" },
      { type: "paragraph", text: "Performance trend: " },
      { type: "paragraph", text: "Error trend: " },
      { type: "paragraph", text: "Usage trend: " },
    ],
  },
];

/**
 * Get a random selection of topics, ensuring variety across categories
 */
export function getRandomTopics(count: number = 10): TemplateTopic[] {
  // Shuffle topics
  const shuffled = [...TEMPLATE_TOPICS].sort(() => Math.random() - 0.5);
  
  // Try to get diverse categories
  const selected: TemplateTopic[] = [];
  const usedCategories = new Set<string>();
  
  // First pass: get one from each category
  for (const topic of shuffled) {
    if (selected.length >= count) break;
    if (!usedCategories.has(topic.category)) {
      selected.push(topic);
      usedCategories.add(topic.category);
    }
  }
  
  // Second pass: fill remaining slots
  for (const topic of shuffled) {
    if (selected.length >= count) break;
    if (!selected.includes(topic)) {
      selected.push(topic);
    }
  }
  
  return selected.slice(0, count);
}

/**
 * Get all available topics
 */
export function getAllTopics(): TemplateTopic[] {
  return TEMPLATE_TOPICS;
}

/**
 * Get topics by category
 */
export function getTopicsByCategory(category: string): TemplateTopic[] {
  return TEMPLATE_TOPICS.filter(topic => topic.category === category);
}

/**
 * Get available categories
 */
export function getCategories(): string[] {
  const categories = new Set(TEMPLATE_TOPICS.map(t => t.category));
  return Array.from(categories);
}
